name: Build DeviousDevices

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  PROJECT_NAME: DDNG

jobs:
  build-skse:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: lukka/get-cmake@latest

    - name: Cache vcpkg packages
      uses: lukka/run-vcpkg@v11
        
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: build-release-msvc
        configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE:STRING=C:/vcpkg/scripts/buildsystems/vcpkg.cmake']"
        buildPreset: release-msvc
    
    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-DLL
        path: |
          build/release-msvc/DeviousDevices.dll
          build/release-msvc/DeviousDevices.pdb
        retention-days: 90
